---
vagrant:
  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
  hosts:
    test_server1:
      ansible_host: 192.168.71.2
    test_server2:
      ansible_host: 192.168.71.3
    test_server3:
      ansible_host: 192.168.71.4
    test_server4:
      ansible_host: 192.168.71.5
